In [1]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.interpolate import LinearNDInterpolator

In [2]:
bi_data = np.load("glam_bk_0114.npz")

In [3]:
kkk = bi_data["k"]
bi_mean = bi_data["bkrm"]
bi_cov = np.cov(bi_data["bkr"])

In [5]:
kkk

array([[0.005, 0.005, 0.005],
       [0.005, 0.015, 0.015],
       [0.005, 0.025, 0.025],
       ...,
       [0.285, 0.285, 0.295],
       [0.285, 0.295, 0.295],
       [0.295, 0.295, 0.295]])

In [4]:
bi_int = LinearNDInterpolator(kkk, bi_mean)

In [5]:
kmax = 0.21
mask = np.ones(2600, dtype=bool)
mask[kkk[:,2] > kmax] = False
cov = bi_cov[np.ix_(mask,mask)]
icov = np.linalg.inv(cov)

In [6]:
Delta = bi_mean[mask] - bi_int(1.002*kkk[mask])
np.dot(np.dot(Delta,icov),Delta)

2.035292274777871

In [21]:
kmax = np.linspace(0.21, 0.25, 5)
alpha = np.linspace(1.0000, 1.0200, 201)
sigma_alpha = np.zeros(np.size(kmax))
sigma_lapha_h = np.zeros(np.size(kmax))
h_factor = np.zeros(np.size(kmax))
for i in range(np.size(kmax)):
    mask = np.ones(2600, dtype=bool)
    mask[kkk[:,2] > kmax[i]] = False
    h_factor[i] = (925 - 1)/(925 - np.sum(mask) -1);
    cov = bi_cov[np.ix_(mask,mask)]
    icov = np.linalg.inv(cov)
    for j in range(np.size(alpha)):
        Delta = bi_mean[mask] - bi_int(alpha[j]*kkk[mask])
        chi2 = np.dot(np.dot(Delta,icov),Delta)
        if chi2 > 1:
            sigma_alpha[i] = alpha[j];
            break;


In [22]:
kmax

array([0.21, 0.22, 0.23, 0.24, 0.25])

In [23]:
sigma_alpha

array([1.0015, 0.    , 1.0001, 1.0001, 1.0001])

In [14]:
sigma_alpha_h

array([0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ,
       0.   , 0.   , 1.089, 1.077, 1.058, 1.045, 1.039, 1.034, 1.033,
       1.03 , 1.029])

In [24]:
h_factor

array([-42.        ,  -6.        ,  -3.10067114,  -2.03524229,
        -1.48314607])

In [13]:
kmax = np.linspace(0.01, 0.2, 20)
alpha = np.linspace(1.000, 1.100, 101)
sigma_alpha = np.zeros(np.size(kmax))
sigma_alpha_h = np.zeros(np.size(kmax))
h_factor = np.zeros(np.size(kmax))
for i in range(np.size(kmax)):
    mask = np.ones(2600, dtype=bool)
    mask[kkk[:,2] > kmax[i]] = False
    h_factor[i] = (925 - 1)/(925 - np.sum(mask) -1);
    cov = bi_cov[np.ix_(mask,mask)]*h_factor[i]
    icov = np.linalg.inv(cov)
    for j in range(np.size(alpha)):
        Delta = bi_mean[mask] - bi_int(alpha[j]*kkk[mask])
        chi2 = np.dot(np.dot(Delta,icov),Delta)
        if chi2 > 1:
            sigma_alpha_h[i] = alpha[j];
            break;
